# 站点基础信息（SEO + 站点身份）
[project]

site_name = "liWanr"    # 页面头部和浏览器窗口标题中

site_author = "liWanr"  # 站点作者

site_url = "https://liWanr.com/"    # 站点的规范 URL, 用于 SEO 和生成 RSS 源

# 站点的简短描述，通常用于 SEO 和社交媒体预览
site_description = "极客向个人技术站点，内容涵盖编程、网络以及真实项目实践，关注技术落地与设计体验，记录持续探索与长期创作。" 

copyright = """
<div style="font-feature-settings: 'ss04' off;">
&copy; 2024-2026 <strong>liWanr</strong> All Rights Reserved.
<small>
|
<a href="https://icp.gov.moe/?keyword=20260905" style="font-feature-settings: 'ss04' off;" target="_blank">萌ICP备 20260905 号</a>
</small>
</div>
"""

nav = [
    { "Home" = "index.md" },
    { "Recom" =  [
        "recom/epic-open-source-project.md",
        "recom/epic-tools.md",
        "recom/epic-website.md",
    ]},
    { "Blog" = [
        "blog/posts/zip-unzip.md",
        "blog/posts/git-basics.md",
        "blog/posts/use-openvpn-client.md",
        "blog/posts/windows-mount-ubuntu-dir.md",
        "blog/posts/openwrt-sd-wan.md",
        "blog/posts/hackrf-firmware-maint.md",
        "blog/posts/zensical-pro-tips.md",
        "blog/posts/chrome-search-new-tab.md",
        "blog/posts/ubuntu-enable-net.md",
        "blog/posts/dns-explain.md",
        "blog/posts/jetbrains-active-free.md",
        "blog/posts/dual-boot-time-sync.md",
        "blog/posts/usb-secure-boot.md",
    ] },
]

# 添加自定义 CSS 文件, 可添加任意数量的 CSS 文件
extra_css = [
    "assets/stylesheets/extra.css",
    "assets/stylesheets/search.css",
]

# 添加自定义 JavaScript 文件, 可添加任意数量的 JavaScript 文件
extra_javascript = [
    "assets/javascripts/extra.js",
]

# 图标与 Logo 配置
[project.theme.icon]
logo = "local/logo"

# 主题相关配置部分
[project.theme]
font.code = "JetBrains Mono"        # 代码块等宽字体
custom_dir = "overrides"            # 模板覆盖目录，用于自定义主题模板
favicon = "assets/favicon.png"      # 设置浏览器标签页或标题栏显示的图标
language = "zh"                     # 设置语言,zh简中, en英文, zh-Hant繁中, zh-TW台湾
features = [
    # ================= 搜索体验 =================
    "search.highlight",             # 搜索跳转后高亮匹配内容

    # ================= 内容 & 代码体验 ===========
    "content.code.annotate",        # 在代码关键位置添加图标 + 鼠标悬停提示
    "content.code.copy",            # 在代码块中添加一键复制按钮，无需先选中内容
    "content.code.select",          # 允许在代码块中选择特定行范围
    "content.footnote.tooltips",    # 将脚注渲染为行内工具提示（tooltip），无需跳转即可阅读
    "content.tabs.link",            # 同步切换内容标签页标题相同的标签
    "content.tooltips",             # 美化 title 提示渲染

    # ================= 导航体验 ================= https://zensical.org/docs/setup/navigation/
    "navigation.indexes",           # 启用章节索引页功能，允许文档直接挂载到章节下（适合概览页）
    "navigation.path",              # 显示路径面包屑导航（在页面标题上方）
    "navigation.tabs",              # 在大屏幕下，将顶级章节渲染为头部下方的菜单标签页
    "navigation.tabs.sticky",       # 启用粘性标签页：向下滚动时标签页固定在头部下方始终可见
    "navigation.top",               # 当用户向下滚动后开始向上滚动时，显示“返回顶部”按钮
    "navigation.tracking",          # 启用锚点跟踪：地址栏 URL 会自动更新为当前高亮的目录锚点
    "toc.follow",                   # 目录锚点跟随：侧边栏会自动滚动，让当前激活的锚点始终可见
]

# 配色方案（palette）配置，可设置自动、明、暗模式切换等
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "跟随系统"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "浅色模式"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "深色模式"

# Markdown 扩展（全部逐项标注用途）
[project.markdown_extensions.abbr]                      # 启用缩写支持
[project.markdown_extensions.admonition]                # 启用提示块（note、warning 等）
[project.markdown_extensions.attr_list]                 # 启用属性列表（用于按钮、class 等）
[project.markdown_extensions.def_list]                  # 启用定义列表语法
[project.markdown_extensions.footnotes]                 # 启用脚注语法支持
[project.markdown_extensions.md_in_html]                # 允许在 HTML 中写 Markdown
[project.markdown_extensions.tables]                    # 启用 Markdown 表格支持
[project.markdown_extensions.toc]                       # 启用目录锚点永久链接
permalink = "⚓︎"
permalink_title = "锚点"

[project.markdown_extensions.pymdownx.blocks.caption]   # 图片标题与对齐支持
[project.markdown_extensions.pymdownx.caret]            # 启用上标/下标语法
[project.markdown_extensions.pymdownx.details]          # 允许提示块折叠
[project.markdown_extensions.pymdownx.inlinehilite]     # 启用行内代码高亮
[project.markdown_extensions.pymdownx.keys]             # 启用键盘按键高亮显示
key_map = {"a"= "a", "b"= "b", "c"= "c", "d"= "d", "e"= "e", "f"= "f", "g"= "g", "h"= "h", "i"= "i", "j"= "j", "k"= "k", "l"= "l", "m"= "m", "n"= "n", "o"= "o", "p"= "p", "q"= "q", "r"= "r", "s"= "s", "t"= "t", "u"= "u", "v"= "v", "w"= "w", "x"= "x", "y"= "y", "z"= "z", "A"= "A", "B"= "B", "C"= "C", "D"= "D", "E"= "E", "F"= "F", "G"= "G", "H"= "H", "I"= "I", "J"= "J", "K"= "K", "L"= "L", "M"= "M", "N"= "N", "O"= "O", "P"= "P", "Q"= "Q", "R"= "R", "S"= "S", "T"= "T", "U"= "U", "V"= "V", "W"= "W", "X"= "X", "Y"= "Y", "Z"= "Z", "asterisk"="*", "at"="@","and"="&","sharp"="#", "percent"="%", "caret"="^"}

[project.markdown_extensions.pymdownx.mark]             # 启用文本高亮标记
[project.markdown_extensions.pymdownx.tilde]            # 启用删除线与下标语法
[project.markdown_extensions.pymdownx.smartsymbols]     # 将某些字符序列转换为相应的符号，例如版权符号或分数

# [project.markdown_extensions.pymdownx.arithmatex]
# generic = true                                          # 启用数学公式渲染（Arithmatex）

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"       # 使用 Twemoji 表情集
emoji_generator = "zensical.extensions.emoji.to_svg"    # 将 emoji 渲染为 SVG
options.custom_icons = ["overrides/.icons"]             # 自定义 SVG 图标目录

[project.markdown_extensions.pymdownx.highlight]
guess_lang = true
# linenums = true                                         # 为所有代码块添加行号
linenums_style = "pymdownx-inline"                      # 行号样式
auto_title = false                                      # 自动为所有代码块添加标题 ，显示所用语言的名称
line_spans = "__span"                                   # 用于行级高亮的 span 标识
anchor_linenums = true                                  # 允许代码行号作为锚点
pygments_lang_class = true                              # 给代码块添加语言 class

[project.markdown_extensions.pymdownx.snippets]
auto_append = ["includes/abbreviations.md"]             # 自动引入缩写定义文件

[project.markdown_extensions.pymdownx.superfences]      # 启用 Mermaid 图表
custom_fences = [{name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }]    

[project.markdown_extensions.pymdownx.magiclink]        # 启用魔法链接
[project.markdown_extensions.pymdownx.blocks.html]      # 启用自定义 HTML 块支持
[project.markdown_extensions.pymdownx.progressbar]      # 启用进度条支持
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true                                  

[project.markdown_extensions.pymdownx.tabbed.slugify]
object = "pymdownx.slugs.slugify"
case = "lower"

[project.markdown_extensions.pymdownx.tasklist]         # 使用自定义复选框样式
custom_checkbox = true

# 其他杂项设置
[project.extra]
generator = false                                       # 移除 “Made with Zensical” 声明

[project.extra.analytics]
provider = "google"
property = "G-JJZ9XN4L96"

[project.extra.analytics.feedback]
title = "这页内容对你有帮助吗？"

[[project.extra.analytics.feedback.ratings]]
icon = "material/emoticon-happy-outline"
name = "有帮助"
data = 1
note = "感谢你的反馈！我很开心这篇文章对你有用(^_^)"

[[project.extra.analytics.feedback.ratings]]
icon = "material/emoticon-sad-outline"
name = "没太大帮助"
data = 0
note = """
感谢你的反馈！我会继续改进的/(ㄒoㄒ)/~~
"""

[project.extra.annotate]
Bash = [".s2"]

[project.extra.tags]                    # 使用标签对任何页面进行分类，标签将作为页面元数据的一部分
Git = "Git"
Server = "Server"
Network = "Network"
Minecraft = "Minecraft"

[project.extra.consent]                 # Cookie 标题和内容描述
title = "隐私与 Cookie 设置"
description = """
    为了让你在这里的体验更加顺畅,
    我使用了 cookies 来记住你的喜好和浏览习惯,
    让你每次访问都能更轻松地找到需要的信息。
    感谢你的支持！
"""

[project.extra.status]
new = "最新发布"

# ----  本地部署的底部链接  ----

[[project.extra.social]]
icon = "material/folder"
link = "/public/"
name = "Public"

[[project.extra.social]]
icon = "material/folder-lock"
link = "/private/"
name = "Private"

[[project.extra.social]]
icon = "simple/openwrt"
link = "http://10.0.0.1"
name = "Openwrt"

[[project.extra.social]]
icon = "lucide/hard-drive-upload"
link = "http://10.0.0.1:16601"
name = "Lucky"

[[project.extra.social]]
icon = "simple/emby"
link = "http://10.0.0.196:8096"
name = "Emby"

[[project.extra.social]]
icon = "material/google-translate"
link = "https://translate.google.com/?hl=zh-CN&sl=zh-CN&tl=en&op=translate"
name = "Translate"